### ISSUE TITLE
Listar Tarefas Disponíveis

### ISSUE THREAD

**Issue by rachelpizane** [StartDB/db-desafio-rachel-gustavo#25]
## Front-end
#26 

## Back-end
#24

**Comment by gusilvo** [comment]
FALTA DEIXAR EM ORDEM

**Comment by rachelpizane** [comment]
Listar tarefas e filtrá-las foram concluidas

![image](https://github.com/user-attachments/assets/39360b91-a104-4cbb-aff7-3bcdfe1c6222)
