### ISSUE TITLE
Inicialização do sistema 

### ISSUE THREAD

**Issue by rachelpizane** [StartDB/db-desafio-rachel-gustavo#3]
- [x] - Criação/Teste base do sistema
- [x] - Docker Compose para levantar o sistema junto

**Comment by gusilvo** [comment]
![image](https://github.com/user-attachments/assets/daca4b14-a9a8-4146-b579-9e7443d2d337)
 tem que ver um jeito de inicializar o banco de dados em ambos pcs quando for criar o docker-compose

**Comment by gusilvo** [comment]
![image](https://github.com/user-attachments/assets/7ab9e78a-602f-43e9-a6c0-7e11051857a6)

um tipo de solução

**Comment by gusilvo** [comment]
> ![image](https://private-user-images.githubusercontent.com/169389502/393968480-7ab9e78a-602f-43e9-a6c0-7e11051857a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4MzkzMTIsIm5iZiI6MTczMzgzOTAxMiwicGF0aCI6Ii8xNjkzODk1MDIvMzkzOTY4NDgwLTdhYjllNzhhLTYwMmYtNDNlOS1hNmMwLTdlMTEwNTE4NTdhNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMFQxMzU2NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOGRmOTg4YmEzMDhiZjJhZTM5ZjFkMDE4ZjU5MGMyZTZlNGYwNDRmMDRkMzFiMDIwMDE5NjVmNDU3NzhmZjQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3wxI69oGJVYl6nD3dkae7aYUxp70l5HRA_QGkDSZLRE)
> 
> um tipo de solução

o próprio docker cria um "usuário e senha" no postgres, então não é necessário essa preocupação

**Comment by rachelpizane** [comment]
Integração realizada com sucesso. Consegui enviar os dados do usuário para o backend.

![Image](https://github.com/user-attachments/assets/2c480272-9d9a-49d1-8b49-4284dcc6c000)

**Comment by gusilvo** [comment]
![image](https://github.com/user-attachments/assets/db929d45-95fd-44b4-9d58-7fd7241087b2)

- [] Problema na inicialização do Postgresql no pc da Rachel

**Comment by gusilvo** [comment]
![image](https://github.com/user-attachments/assets/345d4e36-94a7-4b83-a8fc-b2dc98f98b35)

**Comment by gusilvo** [comment]
<img width="930" alt="image" src="https://github.com/user-attachments/assets/9eb8e146-1592-4556-b57e-96baee25a2e9">

**Comment by gusilvo** [comment]
amanhã, tentar adicionar o {} no docker-compose

**Comment by gusilvo** [comment]
Foi resolvido apenas excluindo o volume e, então, o sistema criou um novo.

O problema estava no fato que não tinha arquivos como postgresql.auto.conf e outros
