### ISSUE TITLE
Registrar cadastro no backend

### ISSUE THREAD

**Issue by rachelpizane** [StartDB/db-desafio-rachel-gustavo#4]
# Front-End
- [x] - Criar página de cadastro puro HTML
- [x] - Alimentar a API do Back End com o cadastro do idoso
- [x] - Alimentar a API do Back End com o cadastro do voluntario

# Back-End
- [x] - Criar entidade User
- [x] - Criar Controller/Repository/Service
- [x] - Criar end-point para registrar o cadastro.

# Geral
Conclusões após o dia 10/12/2024

- [ ] #10

- [ ] #11

- [ ] #12

Co-authored-by: @rachelpizane

**Comment by gusilvo** [comment]
Problema com @Enumerated(EnumType.String), está salvando em inteiro e se tento fazer salvar em String da um erro.
![image](https://github.com/user-attachments/assets/b357cd78-dca4-40ba-885b-f3d310d24546)

**Comment by gusilvo** [comment]
![image](https://github.com/user-attachments/assets/adead910-fe08-46c2-bf98-ecaf941a05f8)

Conclusões da daily:

- [ ] Validações pendentes

- [ ] Persistir o voluntário com Controller, Repository, Service

- [ ] Conectar API via CEP para o Cadastro

Co-authored-by: @rachelpizane

**Comment by gusilvo** [comment]
Conclusões da daily:

- [ ] Validações pendentes

- [ ] Persistir o voluntário com Controller, Repository, Service

- [ ] Conectar API via CEP para o Cadastro

Co-authored-by: @rachelpizane
