### ISSUE TITLE
Tarefa salva como online, mas retorna presencial.

### ISSUE THREAD

**Issue by rachelpizane** [StartDB/db-desafio-rachel-gustavo#75]
Tentei salvar uma tarefa que fosse do tipo online (isOnline:true), mas quando a puxo novamente ela retorna com "isOnline: false". Segue abaixo prints.

[1] - Salvando a tarefa
![image](https://github.com/user-attachments/assets/5c8043e2-44d3-44a6-8eef-6031fc7c1346)

[2] - Retornando a tarefa pelo getTask
![image](https://github.com/user-attachments/assets/f1c85f0a-636b-425c-9769-06e4f9bd1e43)

[3] - Retornando a tarefa pela lista de tarefas disponíveis
![image](https://github.com/user-attachments/assets/6e6694e3-d6a4-4b04-be71-0a00516b7fc6)

**Comment by gusilvo** [comment]
Corrigido! problema era no get e set IsOnline
